anar_blog_panel_login:
    path:     /login
    defaults: { _controller: AnarEngineBundle:Security:loginForm }
    host:     "%router.request_context.host%"

anar_blog_panel_login_check:
    path:     /login_check
    host:     "%router.request_context.host%"

anar_blog_panel_logout:
    path:     /logout
    host:     "%router.request_context.host%"

anar_blog_panel_group:
    resource: "@AnarBlogPanelBundle/Resources/config/routing/group.yml"
    prefix:   /group

anar_blog_panel_log:
    path:     /logs/{page}
    defaults: { _controller: AnarBlogPanelBundle:Log:index, page: 1 }
    requirements: { page: \d+ }

anar_blog_panel_home_blog:
    path:     /{_locale}/{blogName}
    defaults:
        _controller: AnarBlogPanelBundle:Desktop:home
        _locale: fa
    requirements:
        blogName: "[a-z]{4,100}"

anar_blog_panel_home:
    path: /{_locale}
    defaults:
        _controller: AnarBlogPanelBundle:Desktop:home
        _locale: fa
