services:
    anar_blog_panel.listener.authentication:
        class: Anar\BlogPanelBundle\EventListener\AuthenticationListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }