services:
    anar_engine.manager.blog:
        class: Anar\EngineBundle\Doctrine\BlogManager
        arguments: ['@doctrine', '@request_stack', '@security.token_storage', '@anar_engine.manager.language']

    anar_engine.manager.language:
        class: Anar\EngineBundle\Doctrine\LanguageManager
        arguments: ['@doctrine', '@request_stack', "%locale%", "%languages%"]