anar_professor_backend_students_dissertation:
    resource: "@AnarProfessorBundle/Resources/config/routing/backend/studentsdissertation.yml"
    prefix:   /blogpanel/professor/students/dissertation
    options:
        i18n: false

anar_professor_backend_profile:
    resource: "@AnarProfessorBundle/Resources/config/routing/backend/profile.yml"
    prefix:   /blogpanel/professor/profile
    options:
        i18n: false

anar_professor_backend_plan:
    resource: "@AnarProfessorBundle/Resources/config/routing/backend/plan.yml"
    prefix:   /blogpanel/professor/plan
    options:
        i18n: false

anar_professor_frontend_profile:
    resource: "@AnarProfessorBundle/Resources/config/routing/frontend/profile.yml"
    requirements: { blogName: "[a-z]{4,100}" }