anar_super_panel_security:
    resource: "@AnarSuperPanelBundle/Resources/config/routing/login.yml"

anar_super_panel_user:
    resource: "@AnarSuperPanelBundle/Resources/config/routing/user.yml"
    prefix:   /user

anar_super_panel_blog:
    resource: "@AnarSuperPanelBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

anar_super_panel_setting:
    resource: "@AnarSuperPanelBundle/Resources/config/routing/setting.yml"
    prefix:   /setting

anar_super_panel_status:
    path:     /status
    defaults: { _controller: AnarSuperPanelBundle:Desktop:status }

anar_super_panel_home:
    path:     /{_locale}
    defaults:
        _controller: AnarSuperPanelBundle:Desktop:home
        _locale: fa
