liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: images

    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/"

    filter_sets:
        cache: ~
        slideshow:
            filters:
                thumbnail: { size: [1343, 890], mode: outbound }