logout:
    path: /logout
    options: { i18n: false }

anar_engine_bundle:
    resource: "@AnarEngineBundle/Resources/config/routing.yml"
    options: { i18n: false }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options: { i18n: false }

#anar_message:
#    resource: "@AnarMessageBundle/Resources/config/routing.yml"

anar_contact:
    resource: "@AnarContactBundle/Resources/config/routing.yml"

#anar_complaint:
#    resource: "@AnarComplaintBundle/Resources/config/routing.yml"

anar_slide_show:
    resource: "@AnarSlideShowBundle/Resources/config/routing.yml"

anar_menu:
    resource: "@AnarMenuBundle/Resources/config/routing.yml"

anar_professor:
    resource: "@AnarProfessorBundle/Resources/config/routing.yml"

anar_link:
    resource: "@AnarLinkBundle/Resources/config/routing.yml"

anar_content:
    resource: "@AnarContentBundle/Resources/config/routing.yml"

anar_super_panel:
    resource: "@AnarSuperPanelBundle/Resources/config/routing.yml"
    prefix:   /superpanel
    options: { i18n: false }

anar_blog_panel:
    resource: "@AnarBlogPanelBundle/Resources/config/routing.yml"
    prefix:   /blogpanel
    options: { i18n: false }

anar_home:
    resource: "@AnarHomeBundle/Resources/config/routing.yml"