anar_content:
    resource: "@AnarContentBundle/Resources/config/routing.yml"
    prefix:   /

anar_super_panel:
    resource: "@AnarSuperPanelBundle/Resources/config/routing.yml"
    prefix:   /superpanel

