security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        admin_provider:
            entity:
                class: Anar\EngineBundle\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        super_panel_login:
            pattern: ^/superpanel/login$
            anonymous: ~
        super_panel:
            pattern: ^/superpanel
            form_login:
                provider: admin_provider
                csrf_provider: form.csrf_provider
                login_path: anar_super_panel_login
                check_path: anar_super_panel_login_check
                default_target_path: anar_super_panel_home
                always_use_default_target_path: true
            logout:
                path: anar_super_panel_logout
                target: anar_super_panel_home
        blog_panel_login:
            pattern: ^/blogpanel/login$
            anonymous: ~
        blog_panel:
            pattern: ^/blogpanel
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: anar_blog_panel_login
                check_path: anar_blog_panel_login_check
                default_target_path: anar_blog_panel_home
                always_use_default_target_path: true
            logout:
                path: anar_blog_panel_logout
                target: anar_blog_panel_home
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: anar_engine_bundle_login
                check_path: anar_engine_bundle_login_check
            logout:
                path: logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/blogpanel/login$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superpanel/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superpanel, role: ROLE_SUPER_ADMIN }
