services:
    anar_file_manager:
        class: Anar\FileManagerBundle\EventListener\FileManager
        arguments: ["@anar_engine.manager.blog", "@vbee.manager.setting", "@session", "@security.token_storage", "@doctrine"]
