Anar\SlideShowBundle\Entity\Image:
    properties:
        image:
            - NotBlank: ~
            - Type: string
            - Length:
                max: 255
        description:
            - Type: string
            - Length:
                max: 255
        blog:
            - NotNull: ~
            - Type: Anar\EngineBUndle\Entity\Blog