Anar\LinkBundle\Entity\Category:
    type: entity
    table: link_category
    repositoryClass: CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name: ~
        position: ~
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        createdBy:
            gedmo:
                blameable:
                    on: create
        updatedBy:
            gedmo:
                blameable:
                    on: update
    manyToOne:
        blog:
            targetEntity: Anar\EngineBundle\Entity\Blog
            joinColumn:
                name: blog_id
                referencedColumnName: id
                onDelete: cascade
    oneToMany:
        links:
            targetEntity: Link
            mappedBy: category
    lifecycleCallbacks: {  }
