<?php

namespace Anar\MenuBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends NestedTreeRepository
{
    /**
     * @param int $blogId blog id.
     * @param int|null $parent parent id
     * @param array $selected selected menus
     * @return array
     */
    public function getTreeForJstreeFilterByBlog($blogId, $parent = null, $locale='fa', array $selected=array())
    {
        $menus = $this->getTreeQuery($blogId, $parent, $locale)->getArrayResult();

        $tree = array();
        foreach ($menus as $menu) {
            if (is_array($menu['parent'])) {
                $parent = $menu['parent']['id'];
            } else {
                $parent = '#';
            }

            $tree[] = array(
                'id' => $menu['id'],
                'parent' => $parent,
                'text' => $menu['name'],
                'state' => array('selected' => in_array($menu['id'], $selected) ? true : false)
            );
        }

        return $tree;
    }

    /**
     * return query that show menu's tree.
     *
     * @param int $blogId blog id.
     * @param null|int $parent
     * @param string $locale
     * @return \Doctrine\ORM\Query
     */
    public function getTreeQuery($blogId, $parent = null, $locale='fa')
    {
        $qb = $this->createQueryBuilder('m')->select('m', 'p');
        $qb->leftJoin('m.parent', 'p');
        $qb->where($qb->expr()->eq('m.blog', '?1'))
            ->setParameter(1, $blogId);

        if (!is_null($parent)) {
            $qb->andWhere($qb->expr()->eq('m.parent', ':parent'));
            $qb->setParameter('parent', $parent);
        }

        $query = $qb->getQuery();

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $locale
        );

        return $query;
    }

}
