Anar\EngineBundle\Entity\App:
    type: entity
    table: sys_app
    repositoryClass: Anar\EngineBundle\Entity\AppRepository
    gedmo:
        translation:
            locale: currentLocale
            entity: AppTranslation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            unique: true
        title:
            gedmo:
                - translatable
        type: ~
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToMany:
        blogs:
            targetEntity: Blog
            mappedBy: apps
    oneToMany:
        roles:
            targetEntity: Anar\EngineBundle\Entity\Role
            mappedBy: app
        translations:
            targetEntity: AppTranslation
            mappedBy: object

    lifecycleCallbacks: {  }
