Anar\EngineBundle\Entity\App:
    type: entity
    table: sys_app
    repositoryClass: Anar\EngineBundle\Entity\AppRepository
    gedmo:
        translation:
#            locale: currentLocale
            entity: AppTranslation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name: ~
        title:
            gedmo:
                - translatable
        type: ~
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    manyToMany:
        blogs:
            targetEntity: Blog
            mappedBy: apps
    oneToMany:
        translations:
            targetEntity: AppTranslation
            mappedBy: object

    lifecycleCallbacks: {  }
