Anar\EngineBundle\Entity\Blog:
    type: entity
    table: blog
    repositoryClass: Anar\EngineBundle\Entity\BlogRepository
    entityListeners:
        Anar\EngineBundle\EventListener\Doctrine\BlogListener: ~
    gedmo:
        tree:
            type: nested
        translation:
            locale: currentLocale
            entity: BlogTranslation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            gedmo:
                - translatable
        description:
            length: 500
            nullable: true
            gedmo:
                - translatable
        name:
            unique: true
            length: 100
        onTree:
            type: boolean
            column: on_tree
            options:
                default: true
        active:
            type: boolean
            options:
                default: true
        lft:
            type: smallint
            gedmo:
                - treeLeft
        rgt:
            type: smallint
            gedmo:
                - treeRight
        root:
            type: smallint
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: smallint
            gedmo:
                - treeLevel
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Blog
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: restrict
            gedmo:
                - treeParent
        theme:
            targetEntity: Theme
            joinColumn:
                name: theme_id
                referencedColumnName: id
                onDelete: restrict
                nullable: false
    oneToMany:
        children:
            targetEntity: Blog
            mappedBy: parent
            orderBy:
                lft: ASC
        translations:
            targetEntity: BlogTranslation
            mappedBy: object
            cascade: ["persist"]
        groups:
            targetEntity: Group
            mappedBy: blog
    manyToMany:
        apps:
            targetEntity: App
            inversedBy: blogs
            joinTable:
                name: blogs_apps
                joinColumns:
                    blog_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    app_id:
                        referencedColumnName: id
                        onDelete: CASCADE
