Anar\EngineBundle\Entity\Group:
    repositoryClass: GroupRepository
    table: groups
    type: entity
    uniqueConstraints:
        groups_name_unique_idx:
            columns: [blog_id, name]
#    gedmo:
#        translation:
#            locale: currentLocale
#            entity: GroupTranslation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        default:
            column: is_default
            type: boolean
            options:
                default: false
        name:
            type: string
#            gedmo:
#                - translatable
        locked:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        createdBy:
            nullable: true
            column: created_by
            gedmo:
                blameable:
                    on: create
        updatedBy:
            nullable: true
            column: updated_by
            gedmo:
                blameable:
                    on: update

    manyToOne:
        blog:
            targetEntity: Blog
            inversedBy: groups
            joinColumn:
                name: blog_id
                referencedColumnName: id
                onDelete: cascade
    oneToMany:
        translations:
            targetEntity: GroupTranslation
            mappedBy: object
            cascade: ["persist"]
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: groups
            joinTable:
                name: groups_roles
                joinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
                        onDelete: cascade
        users:
            targetEntity: User
            mappedBy: groups