Anar\EngineBundle\Entity\Group:
    table: groups
    type: entity
    gedmo:
        translation:
            locale: currentLocale
            entity: GroupTranslation
        tree:
            type: nested
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        default:
            column: is_default
            type: boolean
            options:
                default: false
        name:
            type: string
            gedmo:
                - translatable
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        blog:
            targetEntity: Blog
            inversedBy: groups
            joinColumn:
                name: blog_id
                referencedColumnName: id
                onDelete: cascade
        parent:
            targetEntity: Group
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: restrict
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Group
            mappedBy: parent
            orderBy:
                lft: ASC
        translations:
            targetEntity: GroupTranslation
            mappedBy: object
            cascade: ["persist"]
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: groups
            joinTable:
                name: groups_roles
                joinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
                        onDelete: cascade
