Anar\EngineBundle\Entity\Language:
    type: entity
    table: sys_language
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            length: 20
        code:
            length: 20
        icon: ~
    lifecycleCallbacks: {  }
