Anar\EngineBundle\Entity\Role:
    type: entity
    table: sys_roles
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name: ~
        role:
            unique: true
    manyToOne:
        app:
            targetEntity: App
            nullable: true
            joinColumn:
                name: app_id
                referencedColumnName: id
                onDelete: cascade
    manyToMany:
        groups:
            targetEntity: Group
            mappedBy: roles
