Anar\EngineBundle\Entity\Theme:
    type: entity
    table: sys_theme
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name: ~
    lifecycleCallbacks: {  }
