Anar\EngineBundle\Entity\Theme:
    repositoryClass: ThemeRepository
    type: entity
    table: sys_theme
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name: ~
        direction:
            type: array
            nullable: false
    lifecycleCallbacks: {  }
