Anar\EngineBundle\Entity\User:
    table: users
    type: entity
    repositoryClass: UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fname: ~
        lname: ~
        faname:
            nullable: true
        staffCode:
            type: integer
            column: staff_code
            unique: true
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: users
            joinTable:
                name: user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: cascade
    manyToOne:
        grade:
            targetEntity: Anar\EngineBundle\Entity\Grade
            joinColumn:
                name: grade_id
                referencedColumnName: id
                onDelete: restrict