anar_contact_frontend_new:
    path:     /contact
    defaults: { _controller: AnarContactBundle:Frontend/Contact:new }
    host:     "{blogName}.%router.request_context.host%"
    methods:  [GET]

anar_contact_frontend_create:
    path:     /contact
    defaults: { _controller: AnarContactBundle:Frontend/Contact:create }
    host:     "{blogName}.%router.request_context.host%"
    methods:  [POST]

anar_contact_frontend_new_path:
    path:     /{blogName}/contact
    defaults: { _controller: AnarContactBundle:Frontend/Contact:new }
    methods:  [GET]

anar_contact_frontend_create_path:
    path:     /{blogName}/contact
    defaults: { _controller: AnarContactBundle:Frontend/Contact:create }
    methods:  [POST]