anar_contact_frontend_new:
    path: /
    defaults: { _controller: AnarContactBundle:Frontend/Contact:new }
    methods: [GET]

anar_contact_frontend_create:
    path: /
    defaults: { _controller: AnarContactBundle:Frontend/Contact:create }
    methods: [POST]