anar_super_panel_user_index:
    path:     /{page}
    defaults:
        _controller: "AnarSuperPanelBundle:User:index"
        page: 1
    requirements:
        page: \d+

anar_super_panel_user_search:
    path:     /search/{page}
    defaults:
        _controller: "AnarSuperPanelBundle:User:search"
        page: 1
    requirements:
        page: \d+
    methods: [POST]

anar_super_panel_user_check_username:
    path: /check/{username}
    defaults: { _controller: AnarSuperPanelBundle:User:checkUsername }

anar_super_panel_user_new:
    path:     /new
    defaults: { _controller: "AnarSuperPanelBundle:User:new" }

anar_super_panel_user_create:
    path:     /create
    defaults: { _controller: "AnarSuperPanelBundle:User:create" }
    methods:  POST

anar_super_panel_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnarSuperPanelBundle:User:edit" }

anar_super_panel_user_update:
    path:     /{id}/update
    defaults: { _controller: "AnarSuperPanelBundle:User:update" }
    methods:  [POST, PUT]

anar_super_panel_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnarSuperPanelBundle:User:delete" }
    methods:  [POST, DELETE]
