anar_contact_backend:
    resource: "@AnarContactBundle/Resources/config/routing/backend.yml"
    prefix:   /blogpanel/contact
    options:
        i18n: false

anar_contact_frontend:
    resource: "@AnarContactBundle/Resources/config/routing/frontend.yml"
    defaults: { blogName: "%master_blog%" }
    requirements: { blogName: "[a-z]{4,100}" }