<?php

namespace Anar\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getQueryFilterByBlog($blogId)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->select('a')
            ->where($qb->expr()->eq('a.blog', ':blogId'))
            ->setParameter('blogId', $blogId)
            ->getQuery();
    }

    public function getFilterByBlog($blogId, $limit=10, $offset=1)
    {
        return $this->getQueryFilterByBlog($blogId)
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getResult();
    }

    public function getAllFilterByBlog($blogId)
    {
        return $this->getQueryFilterByBlog($blogId)
            ->getResult();
    }
}
