<?php

namespace Anar\ContactBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function getAllFilterByBlogQueryBuilder($blog)
    {
        return $this->createQueryBuilder('c')
            ->join('c.blog', 'b')
            ->where('b.id = ?1')
            ->setParameter(1, $blog->getId());
    }
}
