Anar\MenuBundle\Entity\MenuTranslation:
    type: entity
    table: menu_translations
    extends: Translation
    uniqueConstraints:
        menu_translations_unique_idx:
            columns: [locale, object_id, field]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        object:
            targetEntity: Menu
            inversedBy: translations
            joinColumn:
                name: object_id
                referencedColumnName: id
                onDelete: cascade
    lifecycleCallbacks: {  }
