<?php

namespace Anar\EngineBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Symfony\Component\VarDumper\VarDumper;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends NestedTreeRepository
{
    /**
     * @param int|null $parent parent id
     * @param boolean|null $active blog status
     * @param boolean|null $onTree whether show blog on tree
     * @param array $selected selected blogs
     * @return array
     */
    public function getTreeForJstree($parent = null, $active=null, $onTree=null, $locale='fa', array $selected=array())
    {
        $blogs = $this->getTreeQuery($parent, $active, $onTree, $locale)->getResult();

        $tree = array();
        foreach ($blogs as $blog) {
            $tree[] = array(
                'id' => (string) $blog->getId(),
                'parent' => ($blog->getParent() == $parent) ? '#' : $blog->getParent()->getId(),
                'text' => $blog->getTitle(),
                'state' => array('selected' => in_array($blog->getId(), $selected) ? true : false)
            );
        }

        return $tree;
    }

    /**
     * return query that show blog's tree.
     *
     * @param null|string $parent
     * @param null|bool $active
     * @param null|bool $onTree
     * @param string $locale
     * @return \Doctrine\ORM\Query
     */
    public function getTreeQuery($parent = null, $active=null, $onTree=null, $locale='fa')
    {
        $qb = $this->createQueryBuilder('b')->select('b');

        if (!is_null($parent)) {
            $qb->where($qb->expr()->eq('b.parent', ':parent'));
            $qb->setParameter('parent', $parent);
        }

        if (!is_null($active)) {
            $qb = $qb->andWhere($qb->expr()->eq('b.active', ':active'))
                ->setParameter('active', $active);
        }

        if (!is_null($onTree)) {
            $qb->andWhere($qb->expr()->eq('b.onTree', ':onTree'))
                ->setParameter('onTree', $onTree);
        }
        $query = $qb->getQuery();

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $locale
        );

        return $query;
    }

}
