anar_content_backend_article:
    resource: "@AnarContentBundle/Resources/config/routing/backend/article.yml"
    prefix:   /blogpanel/content/article
    options:
        i18n: false

anar_content_backend_category:
    resource: "@AnarContentBundle/Resources/config/routing/backend/category.yml"
    prefix:   /blogpanel/content/category
    options:
        i18n: false

anar_content_frontend:
    resource: "@AnarContentBundle/Resources/config/routing/frontend.yml"
    defaults: { blogName: "%master_blog%" }
    host:     "{blogName}.%router.request_context.host%"
    requirements: { blogName: "[a-z]{4,100}" }

anar_content_frontend_path:
    resource: "@AnarContentBundle/Resources/config/routing/frontend.yml"
    prefix:   /{blogName}
    defaults: { blogName: "%master_blog%" }
    requirements: { blogName: "[a-z]{4,100}" }