services:
    anar_content.form.type.article:
        class: Anar\ContentBundle\Form\ArticleType
        arguments: ['@anar_engine.manager.blog', '@doctrine']
        tags:
            - { name: form.type, alias: article }