Anar\ContentBundle\Entity\Article:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [slug, blog]
    properties:
        title:
            - NotBlank: ~
            - Type: string
            - Length:
                max: 255
        slug:
            - NotBlank: ~
            - Type: string
            - Regex:
                pattern: "/[a-zA-Z0-9_]{4,255}/"
            - Length:
                max: 255
        abstract:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 20
                max: 2000
        article:
            - Type: string
            - Length:
                max: 200000
        visit:
            - Type: integer
        enabled:
            - Type: boolean
        publicationStartDate:
            - Date: ~
        publicationEndDate:
            - Date: ~
        image:
            - Type: string
            - Length:
                max: 255
        blog:
            - NotNull: ~
            - Type: Anar\EngineBundle\Entity\Blog
        category:
            - Type: Anar\ContentBundle\Entity\Category

Anar\ContentBundle\Entity\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [slug, blog]
    properties:
        title:
            - NotBlank: ~
            - Type: string
            - Length:
                max: 255
        description:
            - Type: string
            - Length:
                max: 500
        slug:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 4
                max: 255
        parent:
            - Type: Anar\ContentBundle\Entity\Category
        blog:
            - NotNull: ~
            - Type: Anar\EngineBundle\Entity\Blog
